#!/bin/sh
# plex-inotify

case "$1" in
  start|"")

  #start the inotify monitoring daemon
  python3 /usr/local/bin/plex-inotify.py

   ;;
  restart|reload|force-reload)
   echo "Error: argument '$1' not supported" >&2
   exit 3
   ;;
  stop)
   kill `cat /var/run/plex-inotify.pid`
   ;;
  *)
   echo "Usage: plex-inotify [start|stop]" >&2
   exit 3
   ;;
esac